do
    bind "d" "delete"
    bind "h" "hide"
    bind "H" "unhide"
    bind "P" "unparent"
    bind "<" "setmin"
    bind ">" "setmax"
    bind "\\" "nolimits"
    bind "k" "addknob"
    --bind 'K' "breakknob"
    bind "m" "relocate"
    bind "n" "rename"
    bind "z" "check"
    bind "u" "up"
    bind "=" "setvalue"
    bind "+=" "plusequals"
    bind "-=" "minusequals"
    bind "*=" "timesequals"
    bind "/=" "divideequals"
    bind "|" "quantise"
    bind "!" "alert"
    bind "%" "setcolour"
    bind "~" "container"
    bind "^" "bringFront"
    bind "$" "sendBack"

    bind "A" "noteA"
    bind "B" "noteB"
    bind "C" "noteC"
    bind "D" "noteD"
    bind "E" "noteE"
    bind "F" "noteF"
    bind "G" "noteG"
    bind "b" "flatten"
    bind "#" "sharpen"
    return ()

