do
    bind "⌫" "delete"
    bind "⌥h" "hide"
    bind "⇧⌥H" "unhide"
    bind "⇧P" "unparent"
    bind "⇧<" "setmin"
    bind "⇧>" "setmax"
    bind "\\" "nolimits"
    bind "k" "addknob"
    bind "s" "addslider"
    --bind 'K' "breakknob"
    bind "m" "relocate"
    bind "n" "rename"
    bind "z" "check"
    bind "⎋" "up"
    bind "=" "setvalue"
    bind "0" "setzero"
    bind "1" "setone"
    bind "⇧+=" "plusequals"
    bind "-=" "minusequals"
    bind "⇧*=" "timesequals"
    bind "/=" "divideequals"
    bind "⇧|" "quantise"
    bind "⇧!" "alert"
    bind "⇧%" "setcolour"
    bind "⇧~" "setpicture"
    bind "⇧⌥F" "bringFront"
    bind "⇧⌥B" "sendBack"

    bind "⇧A" "noteA"
    bind "⇧B" "noteB"
    bind "⇧C" "noteC"
    bind "⇧D" "noteD"
    bind "⇧E" "noteE"
    bind "⇧F" "noteF"
    bind "⇧G" "noteG"
    bind "b" "flatten"
    bind "⇧#" "sharpen"
    bind "⌥/" "splitcable"
    return ()

