do
    bind 'd' "delete"
    bind 'h' "hide"
    bind 'H' "unhide"
    bind 'P' "unparent"
    bind '<' "setmin"
    bind '>' "setmax"
    bind '\\' "nolimits"
    bind 'a' "addknob"
    bind 'm' "relocate"
    bind 'n' "rename"
    bind 'z' "check"
    bind 'u' "up"
    bind '=' "setvalue"
    bind '|' "quantise"
    bind '!' "alert"
    bind '%' "setcolour"
    bind '~' "container"

    bind 'A' "noteA"
    bind 'B' "noteB"
    bind 'C' "noteC"
    bind 'D' "noteD"
    bind 'E' "noteE"
    bind 'F' "noteF"
    bind 'G' "noteG"
    bind 'b' "flatten"
    bind '#' "sharpen"
    return ()

